import Foundation

/// UTS-46 status of a code point, from the bundled IdnaMappingTable.
enum IDNAStatus: UInt8, Sendable {
    case valid = 0
    case ignored = 1
    case mapped = 2
    case deviation = 3
    case disallowed = 4
    case disallowedSTD3Valid = 5
    case disallowedSTD3Mapped = 6
}

/// The compiled UTS-46 mapping table (generated by `script/UpdateIDNAMapping.swift`
/// from Unicode's `IdnaMappingTable.txt`). Immutable; looked up by binary search.
struct IDNAMapping: Sendable {
    struct Entry: Sendable {
        let start: UInt32
        let end: UInt32
        let status: IDNAStatus
        let mapping: [Unicode.Scalar]
    }

    let version: String
    let entries: [Entry]   // sorted by `start`, non-overlapping

    /// Status (and replacement, for mapped/deviation) of a single code point.
    /// Code points not covered by the table are treated as `disallowed`.
    func status(of scalar: Unicode.Scalar) -> (status: IDNAStatus, mapping: [Unicode.Scalar]) {
        let v = scalar.value
        var lo = 0
        var hi = entries.count - 1
        while lo <= hi {
            let mid = (lo + hi) / 2
            let e = entries[mid]
            if v < e.start { hi = mid - 1 }
            else if v > e.end { lo = mid + 1 }
            else { return (e.status, e.mapping) }
        }
        return (.disallowed, [])
    }
}

extension IDNAMapping {
    /// Lazily loaded bundled table, shared process-wide. `nil` if the resource is
    /// missing or corrupt, in which case callers fall back to a simpler
    /// normalization. `static let` initialization is lazy and thread-safe.
    static let bundled: IDNAMapping? = load()

    private static func load() -> IDNAMapping? {
        guard let url = Bundle.module.url(forResource: "idna_mapping", withExtension: "bin"),
              let data = try? Data(contentsOf: url) else { return nil }
        return parse([UInt8](data))
    }

    static func parse(_ bytes: [UInt8]) -> IDNAMapping? {
        var p = 0
        func u8() -> UInt8? {
            guard p < bytes.count else { return nil }
            defer { p += 1 }
            return bytes[p]
        }
        func u32() -> UInt32? {
            guard p + 4 <= bytes.count else { return nil }
            let v = UInt32(bytes[p]) | UInt32(bytes[p + 1]) << 8
                | UInt32(bytes[p + 2]) << 16 | UInt32(bytes[p + 3]) << 24
            p += 4
            return v
        }

        guard bytes.count > 9, Array(bytes[0..<4]) == Array("IM46".utf8) else { return nil }
        p = 4
        guard let vlen = u8(), p + Int(vlen) <= bytes.count else { return nil }
        let version = String(decoding: bytes[p..<(p + Int(vlen))], as: UTF8.self)
        p += Int(vlen)
        guard let count = u32() else { return nil }

        var entries: [Entry] = []
        entries.reserveCapacity(Int(count))
        for _ in 0..<count {
            guard let start = u32(), let end = u32(),
                  let rawStatus = u8(), let mapLen = u8(),
                  let status = IDNAStatus(rawValue: rawStatus) else { return nil }
            var mapping: [Unicode.Scalar] = []
            mapping.reserveCapacity(Int(mapLen))
            for _ in 0..<mapLen {
                guard let m = u32(), let scalar = Unicode.Scalar(m) else { return nil }
                mapping.append(scalar)
            }
            entries.append(Entry(start: start, end: end, status: status, mapping: mapping))
        }
        return IDNAMapping(version: version, entries: entries)
    }
}
